CREATE SCHEMA INOVATECH;
USE INOVATECH;

CREATE TABLE IF NOT EXISTS CLIENTES(
ID_CLIENTE INT PRIMARY KEY,
NOME_CLIENTE VARCHAR(100) NOT NULL,
CPF_CLIENTE VARCHAR(20) NOT NULL,
TELEFONE_CLIENTE VARCHAR(13) NOT NULL,
DATANASC_CLIENTE VARCHAR(10) NOT NULL,
STATUSFIDELIDADE_CLIENTE VARCHAR(100) NOT NULL,
CEP_CLIENTE VARCHAR(50) NOT NULL,
RUA_CLIENTE VARCHAR(50) NOT NULL,
NUMCASA_CLIENTE VARCHAR(5) NOT NULL,
BAIRRO_CLIENTE VARCHAR(40) NOT NULL,
IDADE_CLIENTE VARCHAR(3) NOT NULL,
UF_CLIENTE CHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
ID_PRODUTO INT PRIMARY KEY,
CATEGORIA_PRODUTO VARCHAR(45) NOT NULL,
QUANTIDADEESTOQUE_PRODUTO VARCHAR(20) NOT NULL,
PREÇO_PRODUTO VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
ID_FORNECEDOR INT PRIMARY KEY,
NOME_FORNECEDOR VARCHAR(100) NOT NULL,
TELEFONE_FORNECEDOR VARCHAR(13) NOT NULL,
CPF_FORNECEDOR VARCHAR(20) NOT NULL,
EMAIL_FORNECEDOR VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS VENDAS(
ID_VENDA INT PRIMARY KEY,
VALOR_VENDA VARCHAR(45) NOT NULL,
FOREIGN KEY(CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
FORMA_PAGAMENTO INT PRIMARY KEY,
DATA_PAGAMENTO DATE NOT NULL,
VALOR_PAGAMENTO VARCHAR(45) NOT NULL,
STATUS_PAGAMENTO VARCHAR(30) NOT NULL,
FOREIGN KEY(VENDA) REFERENCES VENDAS(ID_VENDA)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_VENDAS(
PRIMARY KEY(PRODUTO, VENDA),
FOREIGN KEY(PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
FOREIGN KEY(VENDA) REFERENCES VENDAS(ID_VENDA),
QNTDPRODUTO_VENDA VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_FORNECEDORES(
PRIMARY KEY(PRODUTO, FORNECEDOR),
FOREIGN KEY(PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
FOREIGN KEY(FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR)
);


